---
title: "Try-Catch Flow"
---

- You can create a try-catch flow, to catch any errors that happen during the flow, to do this, just use the `try` method, then all robots that were added below.
- To return to the normal flow, just use `catch`, passing a function that will be executed if an error occurs.

```ts

Factory
  .createFlow(state)
    .try()
      .pipe(FetchImagesRobot)
      .pipe(DownloadImagesRobot)
    .catch(async (error) => {
      console.error("Error fetching images", error);
      // You can also stop the flow calling throw again here
      // throw error;
    })
  .execute()

```